### ISSUE TITLE
bugs found by llvm static analyzer

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/PhotoGrabber#20]
File:	ptp.c
Warning:	line 2012, column 10
Result of 'calloc' is converted to a pointer of type 'unsigned char', which is incompatible with sizeof operand type;  'uint32_t'data = calloc(sizeof(uint32_t),3);

File:	./ptp-pack.c
Warning:	line 252, column 10
Result of 'malloc' is converted to a pointer of type 'unsigned char', which is incompatible with sizeof operand type 'uint32_t' : *data = malloc ((arraylen+1)*sizeof(uint32_t));

**Comment by Vidrep** [comment]
There were 13 errors detected in total, but I only did a copy/paste of 2. Can I zip up the html report and send it to you? It may be worth a look.

**Comment by korli** [comment]
You can attach to this ticket.

**Comment by Vidrep** [comment]
Here it is:
[scan-build-2018-10-08-100614-3418-1.zip](https://github.com/HaikuArchives/PhotoGrabber/files/2465581/scan-build-2018-10-08-100614-3418-1.zip)

**Comment by owenca** [comment]
Here is the summary of the above report. Clang Static Analyzer found 18 potential bugs.
[BugReport.pdf](https://github.com/HaikuArchives/PhotoGrabber/files/2660980/BugReport.pdf)
