### ISSUE TITLE
Scrollbar not working 

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/PhotoGrabber#23]
No scrollbar when the window space is full.

**Comment by diversys** [comment]
![image](https://user-images.githubusercontent.com/1316513/72208588-3cae4400-34b5-11ea-8f3c-7bf8d65a69ed.png)

**Comment by diversys** [comment]
@waddlesplash could it be related to https://git.haiku-os.org/haiku/commit/?id=5b0e5c0ac69c4?

**Comment by waddlesplash** [comment]
Yes.

**Comment by waddlesplash** [comment]
This can probably be fixed by setting B_SCROLL_VIEW_AWARE on the right view.

**Comment by Vidrep** [comment]
Scrolling fixed with commit referenced in previous comment
