### ISSUE TITLE
Mismatched revision number

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/PhotoGrabber#25]
"About" box shows version 2.3.3 revision 1. Current revision shown in HaikuDepot is 2.3.3 revision 4.

**Comment by humdingerb** [comment]
These are two different things. The one in HaikuDepot is the "REVISION" of the haikuports recipe. That one will increase whenever there's a change in the recipe (typo etc.) to trigger a rebuild of the package.

The "revision" shown in the app's About window is an 'internal' revision number provided in its rdef resource file. I haven't yet found a project that actually uses this internal revision number. As it's meant to be used "internally", it's my opinion that it should be removed from the About window. Major,middle and minor verson numbers (2.3.3) should suffice.
